### ISSUE TITLE
Prefab instances have no local identifier in their scene file

### ISSUE THREAD

**Issue by FlaShG** [FlaShG/GitMerge-for-Unity#17]
*(Original issue title: "Test the tool with Unity 5")*

The new scene management inside the editor might break a lot.

**Comment by FlaShG** [comment]
It seems like the m_LocalIdentfierInFile property (used by the ObjectIDFinder) is 0 in Unity 5 for Objects not differing from their Prefab/Asset counterpart. This breaks the ObjectDictionaries system.

**Comment by excaliburHisSheath** [comment]
Heads up: It looks like Unity 5 is going to have a scene merge tool built in: http://blogs.unity3d.com/2015/02/17/production-workflow-improvements/

**Comment by FlaShG** [comment]
Well, so much for that.

**Comment by NickolausDS** [comment]
The article doesn't appear to mention whether their merging tool will be a pro feature or a free one. Is it too early to tell, or would they reference that elsewhere?

**Comment by FlaShG** [comment]
I can't tell. But the line i quoted makes me wonder if their solution is even better than GitMerge. I mea, form what I understood, their tool only does some pre-merge line magic, and maybe doesn't even help with the actual merging process. I think i will go and ask the folks over at Unity Tech about this.

**Comment by FlaShG** [comment]
Please vote here: http://feedback.unity3d.com/suggestions/re-add-local-identifiers-in-scene-file-for-prefab-instances
Without Unity Tech. changing this, the tool will not work in Unity 5 :disappointed:

**Comment by excaliburHisSheath** [comment]
I just tried with the release version of Unity 5, and it seems like `m_LocalIdentfierInFile` is working. The values seem valid and I can confirm by looking at the serialized file that they are still working. At the least merging prefabs still works, though I haven't tried merging scenes. Perhaps they added it back in before the full release?

**Comment by FlaShG** [comment]
The problem is not in merging perfabs, but having prefab instances in a scene.
Those instances do not have their own id within the scene file.
Read more here: http://forum.unity3d.com/threads/how-to-get-the-local-identifier-in-file-for-scene-objects.265686/#post-1974654

I just downloaded 5.0.0f4, and the problem still exists.

**Comment by excaliburHisSheath** [comment]
Ah, okay. Sorry for the confusion.

**Comment by FlaShG** [comment]
Nothing new concerning the feedback post. It has received enough attention to be on the front page in the "most activity" section for some time though. Thanks everyone for voting!

I hope we can have this problem solved so we can work on the tool again.

**Comment by kentmw** [comment]
Any update? Is this tool useful in the current state of Unity?

**Comment by FlaShG** [comment]
I haven't heard of this being changed in Unity, and they probably want to push their own solutions anyway. I also haven't tested in quite a while. If someone finds that this issue is (or can be) solved, I would start working on this project again.

**Comment by FlaShG** [comment]
Would you look at that... five years later.

https://forum.unity.com/threads/how-to-get-the-local-identifier-in-file-for-scene-objects.265686/#post-5269128

I'll check whether this is what we've been waiting for, and if so, get the project up-to-date.

**Comment by FlaShG** [comment]
It looks like this does indeed do the trick. We're back in business!

The issue is hereby resolved, but if someone finds out that it isn't really, feel free to ring the alarm.
