### ISSUE TITLE
adding buttons: get all theirs/ours

### ISSUE THREAD

**Issue by narlee** [FlaShG/GitMerge-for-Unity#49]
addind button: get all theirs/ours
- without this small issue merging continues very slow.

add buttons on merging:
 get all theirs
 get all ours
- without saving (clicking 'fix')!

**Comment by FlaShG** [comment]
To completely override "their" changes with your own, you can simply use "git checkout --ours", and vice versa use "git checkout --theirs" to only use their version and discard "ours".

I'm not sure if additional buttons would improve the tool's workflow. Maybe for GUI users?

**Comment by narlee** [comment]
thanks, I'm know this. but if user want to select lots of all theirs components and get one ours - it will be very slowly!!!!

**Comment by FlaShG** [comment]
To be honest, I don't quite remember when exactly, but this was recently added.
