### ISSUE TITLE
Error with fresh install

### ISSUE THREAD

**Issue by NDrexlAxonom** [FlaShG/GitMerge-for-Unity#61]
Hi there, I just installed your plugin with code straight from this repo and I get the following error:

> Assets\Editor\GitMerge\Utilities\ObjectID.cs(47,24): error CS0103: The name 'GlobalObjectId' does not exist in the current context

I assume something went wrong with your recent juggling of files or something got left out. Any help will do. Thanks!

**Comment by FlaShG** [comment]
Hi,

this package requires Unity 2019.2 or later. Earlier versions do not work and cannot be supported (rel #17).

**Comment by NDrexlAxonom** [comment]
Awesome good to know thanks! The one project of ours I tried it on was 2018.3, the rest were 2019.2+
