### ISSUE TITLE
Duplicates objects

### ISSUE THREAD

**Issue by ariel7590** [FlaShG/GitMerge-for-Unity#63]
Every time I use this tool, it always duplicates objects in my scene and then I have to delete them manually.

**Comment by FlaShG** [comment]
What Unity version are you using?
Do you have any error messages?

**Comment by ariel7590** [comment]
I'm using version 2020.3.30f1
I don't have any error messages.

**Comment by FlaShG** [comment]
Tried it with 2020.3.17f1, was unable to reproduce.
You're trying to merge a scene?
Have you tried setting up a simple example scene for merging - and does the problem persist for that scene?

**Comment by ariel7590** [comment]
Yes, I'm trying to merge a scene.
Actually I tried just now setting a simple example and it worked without any problems for this example.
But for my main project it duplicated the objects that on the scene for some reason.

**Comment by FlaShG** [comment]
I can imagine some scripts executing in edit mode or some package automatically saving a scene under certain conditions. Try deleting objects in the problematic scene until the problems stops occurring, and check what object made the difference.

**Comment by FlaShG** [comment]
That sounds very likely!
I think this issue can be closed for now then.
